services:
  - type: web
    name: noty-server
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: CLIENT_ORIGIN
        sync: false  # Set this in Render dashboard
      - key: MONGO_URI
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true  # Auto-generate secure secret
      - key: GOOGLE_CLIENT_ID
        sync: false  # Set this in Render dashboard
      # Optional SMTP settings
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
